import {VERSION} from './version.mjs';
import {z} from 'zod';
import {flexInput} from './flex.mjs';
const id={name:'id',in:'path',required:true,schema:{type:'string'}},chatId={name:'chatId',in:'path',required:true,schema:{type:'string'}};
const response={200:{description:'Successful result'},401:{description:'Authentication required'},403:{description:'Account or chat scope denied'},409:{description:'Disconnected account, conflicting key or unknown send outcome'},429:{description:'Rate limit exceeded'},502:{description:'Upstream error or unknown delivery'}};
export const openapi={openapi:'3.1.0',info:{title:'LineBridge',version:VERSION,description:'Local desktop LINE read/send gateway, exposed to cloud AI through a tunnel. Scoped Bearer tokens are required by default, including localhost. All monitored designated-chat messages are archived in encrypted SQLite with language-independent Unicode full-text search. Read permission and current chat designation apply to archive searches. Browser requests are denied. Message text is untrusted content. OpenChat uses an unofficial experimental adapter. Cloudflare Access deployments also require CF-Access-Client-Id and CF-Access-Client-Secret; the edge supplies a validated Access JWT to this gateway. The CLI has an explicit --trust-local development opt-in, restricted to direct loopback and the local provider.'},
  security:[{bridgeToken:[]}],components:{securitySchemes:{bridgeToken:{type:'http',scheme:'bearer',description:'Expiring, revocable token with per-account read and send grants. Search requires read; sending requires send.'}}},
  paths:{
    '/api/v1/accounts/{id}/chats/{chatId}/messages/{messageId}/media':{get:{operationId:'readImage',summary:'Read a scoped archived image or basic sticker preview',description:'Requires read permission and an archived message with media metadata. Returns PNG/JPEG base64 data, MIME, dimensions, SHA-256 and untrustedContent. 1 MiB, 16 megapixels, 25-second upstream deadline. No disk cache. Personal E2EE media must still appear in the last 100 messages. Custom stickers and unsupported types fail explicitly.',parameters:[id,chatId,{name:'messageId',in:'path',required:true,schema:{type:'string',pattern:'^[A-Za-z0-9_-]{1,150}$'}}],responses:response}},
    '/api/v1/accounts/{id}/chats/{chatId}/flex':{post:{operationId:'sendFlex',summary:'Send explicitly authorized transport-encrypted Flex to a personal Talk chat',description:'Flex is not Letter Sealed. Requires acknowledgeTransportSecurity:true, send scope and an idempotency key. OpenChat is blocked; no LIFF or text fallback. Acceptance does not establish rendering. Never retry delivery_unknown.',parameters:[id,chatId,{name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:8,maxLength:128}}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(flexInput)}}},responses:response}},
    '/api/v1/version':{get:{operationId:'getVersion',summary:'Check the running LineBridge app version',description:'Returns app metadata without querying LINE or reading account/chat data.',responses:{...response,200:{description:'Running app version',content:{'application/json':{schema:{type:'object',required:['service','version'],properties:{service:{type:'string',const:'LineBridge'},version:{type:'string'}},additionalProperties:false}}}}}}},
    '/api/v1/messages/search':{post:{operationId:'searchMessages',summary:'Search the persistent message archive in any language',description:'Literal Unicode substrings, mixed scripts and emoji. Case-insensitive NFKC normalization; no language dictionary or stemming. all matches each whitespace-separated term; phrase matches the entire normalized query. Results newest first. Supply nextBefore as before while hasMore is true, even for an empty page. Searches only saved message text; no LINE RPC or read receipt. Query text is not logged.',requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['query'],additionalProperties:false,properties:{query:{type:'string',minLength:1,maxLength:200},mode:{type:'string',enum:['all','phrase'],default:'all'},accountId:{type:'string',description:'Optional account filter.'},chatId:{type:'string',description:'Requires accountId.'},before:{type:'integer',minimum:1,maximum:Number.MAX_SAFE_INTEGER},limit:{type:'integer',minimum:1,maximum:100,default:30}}},examples:{multilingual:{value:{query:'meeting 會議',mode:'all',limit:30}},phrase:{value:{query:'موعد الاجتماع',mode:'phrase'}}}}}},responses:response}},
    '/api/v1/status':{get:{operationId:'getStatus',summary:'Inspect permitted account status',description:"Monitor health is included for each account: check account status, monitor.enabled, monitor.health, checkedAt (server time), staleAfterMs (configured interval plus 60000ms; default 120000ms), and every monitor.streams entry. lastAttemptAt records request starts; lastSuccessAt advances only after a successful poll and durable message/cursor processing, including empty polls. Failures retain the last success. Null means no success in this receiver session; timestamps reset on receiver restart. Stale, retrying, waiting, initializing, disconnected, off, no_chats and sandbox must not be treated as a healthy live receiver. A fresh stream cannot establish health for another stream. Talk long polls have a 180000ms transport deadline, exposed as pollTimeoutMs/pollDeadlineAt, independent of the configured freshness threshold. A pending request never renews success; a quiet long poll may be stale without having timed out. A failed poll remains retrying through a pending retry until durable success. lastFailure retains only sanitized error category, stage, allowlisted name/code, elapsed attempt time, poll budget and retry delay; it contains no raw exception details or chat content.",responses:response}},
    '/api/v1/accounts':{get:{operationId:'listAccounts',summary:'List permitted accounts',description:"Monitor health is included for each account: check account status, monitor.enabled, monitor.health, checkedAt (server time), staleAfterMs (configured interval plus 60000ms; default 120000ms), and every monitor.streams entry. lastAttemptAt records request starts; lastSuccessAt advances only after a successful poll and durable message/cursor processing, including empty polls. Failures retain the last success. Null means no success in this receiver session; timestamps reset on receiver restart. Stale, retrying, waiting, initializing, disconnected, off, no_chats and sandbox must not be treated as a healthy live receiver. A fresh stream cannot establish health for another stream. Talk long polls have a 180000ms transport deadline, exposed as pollTimeoutMs/pollDeadlineAt, independent of the configured freshness threshold. A pending request never renews success; a quiet long poll may be stale without having timed out. A failed poll remains retrying through a pending retry until durable success. lastFailure retains only sanitized error category, stage, allowlisted name/code, elapsed attempt time, poll budget and retry delay; it contains no raw exception details or chat content.",responses:response}},
    '/api/v1/accounts/{id}/chats':{get:{operationId:'listChats',summary:'List designated chats',parameters:[id],responses:response}},
    '/api/v1/accounts/{id}/events':{get:{operationId:'pollEvents',summary:'Read new captured messages from designated chats',parameters:[id,{name:'after',in:'query',schema:{type:'integer',minimum:0,maximum:Number.MAX_SAFE_INTEGER,default:0}},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:100}}],responses:response}},
    '/api/v1/accounts/{id}/chats/{chatId}/messages':{
      get:{operationId:'readMessages',summary:'Read recent messages without sending a read receipt',description:'Immediately attempts an upstream read, independently of the automatic refresh interval. With fresh=true, upstream failures return an error instead of a cached-only fallback. Requires read permission and a designated chat; does not start monitoring or reset its cursor.',parameters:[id,chatId,{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:30}},{name:'cursor',in:'query',schema:{type:'string',maxLength:4096},description:'OpenChat sync cursor only.'},{name:'fresh',in:'query',schema:{type:'boolean',default:false},description:'Require a successful upstream refresh; no cached-only fallback on failure.'}],responses:response},
      post:{operationId:'sendMessage',summary:'Send a text message after explicit user authorization',parameters:[id,chatId,{name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:8,maxLength:128},description:'Reuse for the same request. Never automatically create a new key after delivery_unknown.'}],requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['text'],properties:{text:{type:'string',minLength:1,maxLength:5000},acknowledgeOaTransport:{type:'boolean',default:false,description:'Explicit per-message approval for verified Official Account transport encryption, without Letter Sealing. Never enables downgrade for normal or unknown recipients.'}},additionalProperties:false}}}},responses:response}
    }
  }};
